### ISSUE TITLE
Feature Request: new interface zone entry resource

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-panos#74] opened 2018-09-07 22:11 UTC
First, thank you for the fantastic work in this `panos` provider!

We are automating as much as possible, and using the `panos` provider as much as possible. We create zones in one Terraform stack and then call a module to set up new VPN tunnels. Each VPN Connection setup involves, among other resources, a pair of new tunnel interfaces.

Intuitively, we would want to create the new tunnel interfaces inside the module, as they are part of the VPN Connection package/service offering. However, currently we have to move the creation of these two tunnel interfaces outside the module, because currently the only way to include an interface in a zone is by listing the interface in the zone resource (either `panos_zone` or `panos_panorama_zone`). This works, but is sub-optimal.

I'd like to suggest a `panos_zone_interface_attachment` resource type that creates the connection between the ID of the `panos_zone` resource and the ID of the `panos_tunnel_interface`. This type of resource would enable us to then pass the zone resource ID as a variable into our VPN Connection setup module, create the tunnel interface and include it in the zone all from inside the module.

Here's a good illustrative example from the AWS provider:
https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html

**Comment by shinmog** [comment] 2018-09-11 22:48
@erikpaasonen 

I think this is a dupe of #71 (just barely beat you to it, heh)..?

**Comment by erikpaasonen** [comment] 2018-09-11 23:30
Ahh, now that you point it out, I see now how it is a duplicate. I had the nomenclature wrong, `attachment` vs `entry`. I will close this Issue and give a Thumbs-Up over there. Thanks!

**Comment by erikpaasonen** [comment] 2018-10-18 20:38
Reopening this issue because #71 calls out an `_entry` resource to add a new interface to a Virtual Router. This request is instead for adding a new interface to an existing Security Zone. This way both types of resources can be tracked and completed in separate Issues (hope this helps!).

**Comment by shinmog** [comment] 2018-10-18 20:41
@erikpaasonen 
Ok, got it, ty :)

**Closed** 2018-10-25 23:43 UTC
Labels: enhancement

**Comment by shinmog** [comment] 2018-10-26 19:35
@erikpaasonen 
This workflow is supported in the new 1.4.1 provider.
