### ISSUE TITLE
Rules that are positioned relative to other rules cannot be created in parallel with those rules

### ISSUE THREAD

**Issue by gweimer** [terraform-providers/terraform-provider-panos#149] opened 2019-03-12 21:25 UTC
When creating a list of rules, each "before" the previous, it appears many rules are created in parallel, and rules that are positioned "above" a rule that doesn't exist yet are placed at the bottom. If an entire stack of rules is placed at the bottom in this manner, multiple terraform runs are required to move the entire stack to the correct position. (Only the one at the bottom is out of position, so it is moved on next run. Now new bottom rule is out of position because it is supposed to be above the one that just moved.)

**Comment by shinmog** [comment] 2019-03-12 21:28
Can you share a plan file that shows what you're seeing?

**Comment by gweimer** [comment] 2019-03-14 03:16
The plan shows everything correctly, but the run creating multiple rules that are supposed to position based on previous rule (using before) never creates them all in the correct order. The last two attempts to create all the rules put the 1st one in the correct position, but the rest were placed below that rule (I think at the bottom of the rule list, but I forgot to verify) instead of above it. The next run will usually fix 2 or 3 nats. Each successive run will fix more, but I'm adding 10 rules, so they do not all get ordered correctly until I've run terraform quite a few times.

**Comment by gweimer** [comment] 2019-03-14 19:46
As another hint to what is going on: I forgot to add the base rule that all the others are placed above on another FW. When I ran TF to add new rules, it failed to add the 1st one that was to be placed above the missing rule, but it added the next rule that was supposed to be placed above the rule it failed to add. All the remaining rules were also added.

**Comment by shinmog** [comment] 2019-03-18 19:07
@gweimer 

Ok, so if some resources fail while others succeed, this sounds like you're not using resource attribute variables.  If you don't use resource attribute variables, then Terraform does not know it needs to create A before B (before C, etc).

**Comment by shinmog** [comment] 2019-03-18 19:09
If you could share the plan file, I could determine what the issue is.

**Comment by gweimer** [comment] 2019-03-21 19:06
ANCHOR base ANCHOR is expected to be created manually.

resource "panos_nat_rule_group" "SV_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR base ANCHOR"
  rule {
    name = "ANCHOR SV ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "SV", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "RR_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR SV ANCHOR"
  rule {
    name = "ANCHOR RR ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "RR", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "PT_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR RR ANCHOR"
  rule {
    name = "ANCHOR PT ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "PT", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "NE_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR PT ANCHOR"
  rule {
    name = "ANCHOR NE ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "NE", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "MG_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR NE ANCHOR"
  rule {
    name = "ANCHOR MG ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "MG", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "HL_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR MG ANCHOR"
  rule {
    name = "ANCHOR HL ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "GW", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "GW_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR HL ANCHOR"
  rule {
    name = "ANCHOR GW ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "GW", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "EP_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR GW ANCHOR"
  rule {
    name = "ANCHOR EP ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "EP", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "AU_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR EP ANCHOR"
  rule {
    name = "ANCHOR AU ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "AU", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

resource "panos_nat_rule_group" "AL_anchor" {
  position_keyword = "before"
  position_reference = "ANCHOR AU ANCHOR"
  rule {
    name = "ANCHOR AL ANCHOR"
    disabled = true
    description = "Provides an anchor for FW NATs to be before"
    tags = ["ANCHOR", "AL", "Managed-By-Terraform"]
    original_packet {
      source_zones          = ["any"]
      source_addresses      = ["0.0.0.0/32"]
      destination_zone      = "Internet"
      destination_addresses = ["0.0.0.0/32"]
    }
    translated_packet {
      source {}
      destination {}
    }
  }
}

**Comment by shinmog** [comment] 2019-03-21 20:09
@gweimer 

Thanks!  So just to double-check, this is all in a single Terraform plan file?  Or multiple plan files?

**Comment by shinmog** [comment] 2019-03-22 05:36
@gweimer 

Ok, so without knowing the answer, I'll answer a few possible scenarios, because from what you've said the above is part of a single `terraform apply`.

I believe there are two cases:  everything is in one terraform file or it isn't.

If everything is in the same file, then you should make use of the fact that `panos_nat_rule_group` allows you to specify multiple rules.  Besides decluttering the plan file, it has the added benefit of speeding up `terraform plan / apply / destroy` as there is logic to cut down on API calls.

Your terraform plan file would thus look like this (I'll just keep rule names to cut down on the amount of vertical scrolling needed):

```hcl
resource "panos_nat_rule_group" "SV_anchor" {
    position_keyword = "before"
    position_reference = "ANCHOR base ANCHOR"
    rule {
        name = "ANCHOR AL ANCHOR"
    }
    rule {
        name = "ANCHOR AU ANCHOR"
    }
    rule {
        name = "ANCHOR EP ANCHOR"
    }
    rule {
        name = "ANCHOR GW ANCHOR"
    }
    rule {
        name = "ANCHOR HL ANCHOR"
    }
    rule {
        name = "ANCHOR MG ANCHOR"
    }
    rule {
        name = "ANCHOR NE ANCHOR"
    }
    rule {
        name = "ANCHOR PT ANCHOR"
    }
    rule {
        name = "ANCHOR RR ANCHOR"
    }
    rule {
        name = "ANCHOR SV ANCHOR"
    }
}
```

If the NAT rules are in separate files (due to workflow organization), then you should use resource attribute variables that I mentioned before to let Terraform know the correct order of creation.

So you would do this instead:
```hcl
resource "panos_nat_rule_group" "SV_anchor" {
    position_keyword = "before"
    position_reference = "ANCHOR base ANCHOR"
    rule {
        name = "ANCHOR SV ANCHOR"
    }
}

resource "panos_nat_rule_group" "RR_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.SV_anchor.rule.0.name}"
    rule {
        name = "ANCHOR RR ANCHOR"
    }
}

resource "panos_nat_rule_group" "PT_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.RR_anchor.rule.0.name}"
    rule {
        name = "ANCHOR PT ANCHOR"
    }
}

resource "panos_nat_rule_group" "NE_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.PT_anchor.rule.0.name}"
    rule {
        name = "ANCHOR NE ANCHOR"
    }
}

resource "panos_nat_rule_group" "MG_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.NE_anchor.rule.0.name}"
    rule {
        name = "ANCHOR MG ANCHOR"
    }
}

resource "panos_nat_rule_group" "HL_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.MG_anchor.rule.0.name}"
    rule {
        name = "ANCHOR HL ANCHOR"
    }
}

resource "panos_nat_rule_group" "GW_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.HL_anchor.rule.0.name}"
    rule {
        name = "ANCHOR GW ANCHOR"
    }
}

resource "panos_nat_rule_group" "EP_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.GW_anchor.rule.0.name}"
    rule {
        name = "ANCHOR EP ANCHOR"
    }
}

resource "panos_nat_rule_group" "AU_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.EP_anchor.rule.0.name}"
    rule {
        name = "ANCHOR AU ANCHOR"
    }
}

resource "panos_nat_rule_group" "AL_anchor" {
    position_keyword = "before"
    position_reference = "${panos_nat_rule_group.AU_anchor.rule.0.name}"
    rule {
        name = "ANCHOR AL ANCHOR"
    }
}
```

Hope this helps!

**Comment by gweimer** [comment] 2019-03-28 16:31
They are in the same file, but if I use the rule_group, they will be forced to be adjacent. This is not acceptable if they are anchors for grouping other rules that will appear between these rules. I was assuming using the name for position_reference would do the same thing, but I can switch to using the variables instead.

**Comment by shinmog** [comment] 2019-03-28 17:39
@gweimer 
Ah, ok.  Didn't realize the intent was that there was stuff between them.

Then yes, use the second approach where the `position_reference` is a resource attribute variable.  Doing it as resource attribute variables implicitly links the resources together so Terraform knows the order to create things in.  The other way is explicit linking using `depends_on`, but I have a strong preference to not use that if it can be avoided.

Seems like you're set now..?

**Comment by shinmog** [comment] 2019-05-13 23:28
Seems this issue is resolved, so closing.

**Closed by shinmog** 2019-05-13 23:28 UTC
